### ISSUE TITLE
TOKEN complains - but there's no mention in readme.

### ISSUE THREAD

**Issue by johndpope** [scristobal/botatobot#8]
TOKEN, ok = os.LookupEnv("TOKEN")

	if !ok {
		log.Println("TOKEN not found, calls to external APIs might fail")
	}

I have BOT_TOKEN fine - as per readme....

**Comment by scristobal** [comment]
You were absolutely right, it was plain confusing. `TOKEN` was used in case the `URL` was pointing to Replicate.com 

Updated the README to reflect this. Thanks! @johndpope
