### ISSUE TITLE
clarification on cog / dockerfile

### ISSUE THREAD

**Issue by johndpope** [scristobal/botatobot#9]
it seems like this file 
https://github.com/replicate/cog-stable-diffusion/blob/main/cog.yaml

should be included - rather than depending on external docker file 
https://github.com/replicate/cog

then this....
```shell
sudo curl -o /usr/local/bin/cog -L https://github.com/replicate/cog/releases/latest/download/cog_`uname -s`_`uname -m`
sudo chmod +x /usr/local/bin/cog
```

then cog build 

one reason being - the cog file I'm using is referencing cuda 11.6.2 - but I'm on 11.8.

**Comment by scristobal** [comment]
I saw it is a common issue, https://github.com/replicate/cog-stable-diffusion/issues/89 

Better to use cog directly as you suggested, updated the README accordingly. 

Thank you for your feedback! very much appreciated
